port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
#secret: ""
#external-ui: dashboard

dns:
  enable: true
  ipv6: false
  listen: '0.0.0.0:53'
  enhanced-mode: fake-ip
  nameserver:
    - 192.168.50.1 #电信
Proxy:

- { name: "1", type: vmess, server: prov2ss.cnm.workers.dev, port: 443, uuid: ad806487-2d26-4636-98b6-ab85cc8521f7, alterId: 64, cipher: auto, network: ws, ws-path: /, tls: true }
- { name: "2", type: vmess, server: usw1.cnm.workers.dev, port: 443, uuid: ad806487-2d26-4636-98b6-ab85cc8521f7, alterId: 64, cipher: auto, network: ws, ws-path: /ws, tls: true }

Proxy Group:
# url-test 可以自动选择与指定 URL 测速后，延迟最短的服务器
- { name: "PROXY", type: url-test, proxies: ["1", "2"], url: "https://www.bing.com", interval: 300 }

Rule:

# Unbreak
# > Google
- DOMAIN-SUFFIX,google.com,PROXY
# > YouTube及YouTube TV
- DOMAIN-SUFFIX,ggpht.com
- DOMAIN-SUFFIX,googleapis.com
- DOMAIN-SUFFIX,googletagmanager.com
- DOMAIN-SUFFIX,googleusercontent.com
- DOMAIN-SUFFIX,googlevideo.com
- DOMAIN-SUFFIX,gstatic.com
- DOMAIN-SUFFIX,imrworldwide.com
- DOMAIN-SUFFIX,ytimg.com
- DOMAIN-SUFFIX,youtube.com
# > facebook
- DOMAIN-SUFFIX,facebook.com,PROXY
- DOMAIN-SUFFIX,facebook.net,PROXY
- DOMAIN-SUFFIX,fbcdn.net,PROXY
- DOMAIN-SUFFIX,fb.me,PROXY
# > github
- DOMAIN-SUFFIX,github.com,PROXY
- DOMAIN-SUFFIX,githubusercontent.com,PROXY

# > iQiyi
- DOMAIN,t7z.cupid.ptqy.gitv.tv,REJECT
# > 芒果TV
- DOMAIN,da.mgtv.com,REJECT
# > 乐播投屏
- DOMAIN,ad.hpplay.cn,REJECT
- DOMAIN,adeng.hpplay.cn,REJECT
- DOMAIN,rp.hpplay.cn,REJECT
# (M)
# Local Area Network
- IP-CIDR,192.168.0.0/16,DIRECT
- IP-CIDR,10.0.0.0/8,DIRECT
- IP-CIDR,172.16.0.0/12,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- IP-CIDR,100.64.0.0/10,DIRECT
# > Telegram
- DOMAIN-SUFFIX,t.me,PROXY
- DOMAIN-SUFFIX,tdesktop.com,PROXY
- DOMAIN-SUFFIX,telegra.ph,PROXY
- DOMAIN-SUFFIX,telegram.me,PROXY
- DOMAIN-SUFFIX,telegram.org,PROXY
- IP-CIDR,91.108.4.0/22,PROXY
- IP-CIDR,91.108.56.0/22,PROXY
- IP-CIDR,91.108.56.0/23,PROXY
- IP-CIDR,109.239.140.0/24,PROXY
- IP-CIDR,149.154.160.0/22,PROXY
- IP-CIDR,149.154.164.0/22,PROXY
- IP-CIDR,149.154.168.0/22,PROXY
- IP-CIDR,149.154.172.0/22,PROXY
# DNSPod Public DNS+
- IP-CIDR,119.28.28.28/32,DIRECT
# GeoIP China

# 最终规则
- GEOIP,CN,DIRECT
- MATCH,DIRECT
